export const cluster = {
    "API Lifecycle Platform": {
      // ["Access Level and Identity Management",
      // "API Analytics/Monitoring",],
      // "API Documentation",
      // "API Security",
      0: ["API Management/API Gateway", "API Consulting"],
      1: ["API Design/Documentation Platforms"],
      2: ["API Developer Portals", "Streaming/Event Architecture"],
      // "API Testing",
      3: ["IoT Platforms/Networks/Devices"],
    },
    "API Lifecycle (Security Pureplay)": {
      0: ["API Security"],
      1: ["API Threat Management"],
      2: ["API Discovery and Risk Management", "Vulnerability Management"],
    },
    "API Lifecycle (Embedded Security)": {
      0: ["Vulnerability Identification/scanners", "Web Application Firewalls"],
    },
    "API Lifecycle (Adjacent Security Solutions)": {
      0: ["API Analytics/Monitoring"],
      1: ["Identity verification/KYC"],
      2: ["Login", "Access and Identity Management"],
    },
    // "API Standards/Protocols": [
    //   ["AsyncAPI"],
    //   ["FIDO"],
    //   ["GraphQL"],
    //   ["gRPC"],
    //   ["Open API Specs"],
    //   ["OpenID"],
    //   ["PSD2 API Abstractions"],
    //   ["STET Berlin Group"],
    // ],
    "Backend Building Tools": {
      0: ["API Deployment/Back-end Building"],
      1: ["Banking/Finance/Insurance Backends"],
      2: ["Blockchain"],
      3: ["Headless CMS"],
      4: ["Infrastructure/Cloud/Serverless APIs"],
      5: ["Mobile Backend as a Service"],
    },
    "Business processes as an API/API-as-a-Product": {
      0: ["Data"],
      1: ["Email/Messaging/Communications Platforms as a Service", "Payments"],
      2: ["AI/ML", "E-commerce"],
      3: ["Accounting", "Audio/Visual", "Legal/Regulatory"],
      4: ["Data governance/Data management"],
      5: [
        "Forms",
        "Human-as-a-service",
        "Human Resources",
        "Search",
        "Time/Calendar",
      ],
    },
    "Integration Platform as a Service": {
      0: ["API Aggregators (General)"],
      1: ["Automation/Orchestration"],
      2: ["Database-as-a-service", "API Aggregators (Finance)"],
    },
    "Vertical API Abstraction": {
      0: ["Finance", "Healthcare"],
      1: [
        "Marketing/Analytics",
        "Cloud Storage",
        "Delivery/Transport/Logistics",
        "Smart Home/Facilities",
      ],
    },
  };