export const categories = [
    "API Lifecycle Platform",
    "API Standards and Protocols",
    "Backend Building Tools",
    "Business processes as an API/API-as a Product",
    "Integration Platform as a Service",
    "Vertical API Abstractions",
  ];

export const subcategories = [
  "Access and Identity Management",
 "API Analytics/Monitoring",
  "API Design/Documentation Platforms",
  "API Developer Portals",
  "API Management/API Gateway",
  "API Oriented IT Consulting Firms",
  "API Testing",
  "API Security",
  "Streaming & Event Architecture",
  "IoT Platforms/Networks/Devices",
  "Accounting",
  "AI & ML",
  "Audio & Video",
  "Legal & Regulatory",
  "Time & Calendar",
  "Data governance & Data management",
  "E-commerce",
  "Data",
  "Email/Messaging/Communications Platforms as a Service",
  "Forms",
  "Identity verification & KYC",
  "Human Resources",
  "Human-as-a-service",
  "Payments",
  "Search",
  "API protocols",
  "API standards",
  "API Deployment/Back-end Building",
  "Banking/Finance/Insurance Backends",
  "Blockchain",
  "Headless CMS",
  "Infrastructure/Cloud/Serverless APIs",
  "Mobile Backend as a Service",
  "API Aggregators (General)",
  "Automation/Orchestration",
  "Database-as-a-service",
  "API Aggregators (Finance)",
  "Cloud Storage",
  "Delivery/Transport/Logistics",
  "Healthcare",
  "Login",
  "Marketing and Analytics",
  "Finance",
"  Smart Home and Smart Facilities"
  ];